config/routes.rb
Rails.application.routes.draw do
  resources :listings

  get 'pages/about'

  get 'pages/contact'

  root 'listings#index'

end

app/models/listing.rb
class Listing < ActiveRecord::Base 
	if Rails.env.development?
		has_attached_file :image, :styles => { :medium => "200>", :thumb => "100x100>" }, :default_url => "notFound.png",
	else
		has_attached_file :image, :styles => { :medium => "200>", :thumb => "100x100>" }, :default_url => "notFound.png",
				  :storage => :dropbox,
    			  :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
    			  :path =>":style:id_:filename"

validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/    							 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :description, :price, :image)
    end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<p>Copyright 2099</p>

app/views/layouts/_header.html.erb
 <nav class="navbar navbar-default" role="navigation">
 
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Etsydemo</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/pages/about">About<span class="sr-only">(current)</span></a></li>
        <li><a href="/pages/contact">Contact</a></li>
        
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        
        
      </ul>
    </div><!-- /.navbar-collapse -->
 
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Etsydemo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 
	
 <%= render 'layouts/header' %>
 <div class= "container">
<%= yield %>

<%= render 'layouts/footer' %>
</div> <!--end container-->


</body>
</html>

app/views/listings/_form.html.erb
<%= form_for(@listing, :html => { :multipart => true }) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price , class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image , class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-warning" %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<div class= "container">
<h1>Editing listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing, class: "btn btn-link" %> |
<%= link_to 'Back', listings_path, class: "btn btn-link" %>
</div> <!--end container-->

app/views/listings/index.html.erb
<div class="center">
<div class="row">
  <% @listings.each do |listing|%>
    <div class="col-md-3">
      <div class="thumbnail">
        <%= image_tag listing.image.url%>
          <div class="caption">
            <h4> <%= listing.name %></h4>
            <p><%= listing.description %></p>
            <%= number_to_currency(listing.price) %><br/>
           <%= link_to 'Show', listing, class: "btn btn-link"%>
            <%= link_to 'Edit', edit_listing_path(listing), class: "btn btn-link" %>
            <%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %>
          </div>
      </div>    
    </div>
  <% end %>
</div>
</div>
<br>


<%= link_to 'New Listing', new_listing_path %>

app/views/listings/new.html.erb
<h1>New listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path, class: "btn btn-link" %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
	<div class="col-md-6">
		<div class="thumbnail">
<%= image_tag @listing.image.url %>
		</div>
	</div>	
	<div class="col-md-6">
	  	<h3><%= @listing.name %></h3>
	  	<p><%= number_to_currency(@listing.price) %></p>
	  	<p><%= @listing.description %></p>
		<p><%= @listing.description %></p>

	
	  	
		<%= link_to 'Edit', edit_listing_path(@listing), class: "btn btn-link" %> |
		<%= link_to 'Back', listings_path, class: "btn btn-link" %>
	</div>
</div>

app/views/pages/ESIC-ForumCafe.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="remark,remarkjs,markdown,slideshow,presentation" />
    <meta name="description" content="ESIC - Movilizando Redes Comerciales" />
   <meta name="author" content="Santiago Román" />
      <title>Gestión de la información para el análisis externo de la empresa - EAE 12 abril 2014</title>
    <style type="text/css">
      @import url(http://fonts.googleapis.com/css?family=Droid+Serif);
      @import url(http://fonts.googleapis.com/css?family=Yanone+Kaffeesatz);

      body {
        font-family: 'Droid Serif';
        font-size: 20px;
       
        
          }
        
      h1, h2, h3 {
        font-family: 'Yanone Kaffeesatz';
        font-weight: 400;
        margin-bottom: 30;
      }
      h1 { font-size: 4em; }
      h2 { font-size: 2em; }
      h3 { font-size: 1.6em; }
      
    
    .footnote {
        position: absolute;
        bottom: 7em;
        left:400px;
        font-size: 0.8em;
       
      }
      
    li p { line-height: 1.25em; }
    .color { color: #fa0000; }
    .color1{color:#fff;}
    .large { font-size: 2em; }
    
    a, a > code {
        color: #fff;
        text-decoration: underline;
        target:"_blank";
              }
      
    code {
        -moz-border-radius: 5px;
        -web-border-radius: 5px;
        background: #e7e8e2;
        border-radius: 5px;
        font-size: 16px;
      }
    .pull-left {
        float: left;
        width: 47%;
      }
    .pull-right {
        float: right;
        width: 47%;
      }
    .pull-right ~ p {
        clear: both;
      }
    #slideshow .slide .content code {
        font-size: 0.8em;
      }
    #slideshow .slide .content pre code {
        font-size: 0.9em;
        padding: 15px;
      }
        
    .normal{
        background: #fff;
        color: #272822;
        background-repeat: repeat;
        
       
    }
        .normal h1, .normal h2,  .normal h3 {
        color: black;
        line-height: 0.8em;
          
      }
        
        
      .inverse {
        background: #272822;
        color: #f3f3f3;
        text-shadow: 0 0 20px #333;
      }
      .inverse h1{
        color: #ff6452;
        line-height: 0.8em;
      }
        .inverse h2{
        color: #fff;
        line-height: 0.8em;
      }

    .penumbra{color: #777;}
        
      /* Two-column layout */
      .left-column {
        color: #777;
        width: 20%;
        height: 92%;
        float: left;
      }
        .left-column h2:last-of-type, .left-column h3:last-child {
          color: #ff6452;    
        }
      .right-column {
        width: 75%;
        float: right;
        padding-top: 1em;
      }
  
/*Títulos de las secciones*/
        
.title{
    font-size:3em;
    color:#000;
    background-color:#fff;
    
}
        
    </style>
  </head>
  
    
    
    <body>
    <textarea id="source">
name: normal          
layout: true
class: center, middle, normal
---
![Forum Cafe logo](http://www.ivoox.com/canales/3F__rum_del_Caf__g.jpg)
![ESIC logo](http://www.esic.edu/imagenes/logo.png)        
# Movilizando Redes Comerciales
 .footnote[21 enero 2015 <br/>
@santiago_roman]
---

template: normal
background-image:url(http://www.coredigitalworks.com/wp-content/uploads/2014/04/Depositphotos_43350387_m-crop.jpg)
.title[10 ventajas de una fuerza de ventas Móvil]

---
        
# #1 Gestión de Contenidos        
---
# #2 Acortar el ciclo de venta
---
# #3 Acceso a la información
---
# #4 Moviliza tu CRM
---
# #5 Business Intelligence
---
# #6 Agilizar Operaciones
---
# #7 Integración de Sistemas
---
# #8 Colaboración
---
# #9 Apoderar a los clientes
---
# #10 Formación
---
# #11 VENDER MÁS Y MEJOR
---

background-image:url(http://www.signalinc.com/wp-content/uploads/2013/04/mobile_blog_image.jpeg)
.title[Consejos para implementar una Estrategia de Movilidad]      
---
# #1 So You Bought iPads for Sales – Now What?
---
# #2 Transversal a toda la organización
---
# #3 Definir claramente los objetivos 
        
        
---
background-image:url(http://www.gillettepepsicola.com/images/upload/381.jpg)
.footnote[http://youtu.be/A0hCmzbQJSA?list=PLLhTEzkIVvqhfJ8SOmn8p4rZPMgP6V2PS]
         
---
# ¿Preguntas?
@santiago_roman 

    </textarea>
    <script src="https://gnab.github.io/remark/downloads/remark-latest.min.js" type="text/javascript"></script>
    <script type="text/javascript">
      var hljs = remark.highlighter.engine;
    </script>
    <script src="remark.language.js" type="text/javascript"></script>
    <script type="text/javascript">
      var slideshow = remark.create({
          highlightStyle: 'monokai',
          highlightLanguage: 'remark'
        }) ;
    </script>
    
  </body>
</html>

app/views/pages/about.html.erb
<h1>Welcome to EtsyDmeo</h1>
<p>Etsy demo is an online market site</p>

app/views/pages/contact.html.erb
<h1>Email as at santi@gmail.com</h1>
<p>Hola</p>